{{- if .Values.grafana.dashboards.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hyperswitch-monitoring-core.fullname" . }}-grafana-datasource
  labels:
    {{- include "hyperswitch-monitoring-core.labels" . | nindent 4 }}
    grafana_datasource: "1"
data:
  grafana-datasource.yaml: |
    apiVersion: 1
    datasources:
      {{- if .Values.grafana.postgresql.enabled }}
      - name: PostgreSQL
        type: postgres
        access: proxy
        url: {{ .Values.grafana.postgresql.host }}:{{ .Values.grafana.postgresql.port }}
        user: {{ .Values.grafana.postgresql.user }}
        password: {{ .Values.grafana.postgresql.password }}
        database: {{ .Values.grafana.postgresql.database }}
        uid: postgres_uid
        jsonData:
          sslmode: {{ .Values.grafana.postgresql.sslMode | quote }}
        secureJsonData:
          password: {{ .Values.grafana.postgresql.password }}
      {{- end }}
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://{{ .Release.Name }}-kube-prometheus-stack-prometheus:9090
        isDefault: true
        uid: "my-prometheus"
        jsonData:
          timeInterval: "5s"
      - name: Loki
        type: loki
        access: proxy
        url: http://{{ .Release.Name }}-loki:3100
        uid: "loki"
{{- end }}