# https://taskfile.dev

version: '3'


tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  package-incubator-hyperswitch-helm:
    #language=sh
    cmds:
      - >
        STACK=charts/incubator/hyperswitch-stack &&
        version=$(grep '^version:' $STACK/Chart.yaml | awk '{print $2}') &&
        helm package $STACK --dependency-update &&
        helm repo index $STACK --url https://juspay.github.io/hyperswitch-helm/v$version &&
        mkdir -p v$version && mv hyperswitch-stack-$version.tgz $STACK/index.yaml v$version
    aliases:
      - pihh

  repo-update-index:
    #language=sh
    cmds:
      - >
        helm repo index repo 
