# Configuration values used for the deployment of the application
application:
  # The is the configuration that is globally common for all the application related deployments
  global:
    # Number of replicas to be used for the application by default (for server and consumer)
    replicas: 3
    # Wait time allowed for the deployment before the deployment is marked as failed
    progressDeadlineSeconds: 600
    # The strategy that can be used to replace the old pods by new ones
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    # Specify affinity for nodes to which the pods should start on
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - generic-compute
    # The time kubernetes will wait after sending the termination signal to the pods
    terminationGracePeriodSeconds: 30
    # Annotations that are to be added to the pods
    podAnnotations:
      traffic_sidecar_istio_io_excludeOutboundIPRanges: 
    # Annotations that are to be added the the deployments
    annotations:
      deployment.kubernetes.io/revision: "1"
    # Labels to be added to the all the deployments and their pods
    labels:
      managedBy: hyperswitch

    # service account annotations to be used
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: 
    # Environmant variables that are to be used by the hyperswitch application services
    env:
      pod_name: 
        name: POD_NAME
        valueFrom:
          fieldRef:
            apiVersion: v1
            fieldPath: metadata.name

    configMap: |
      [server]
      host = 0.0.0.0

    # secrets to be used by the hyperswitch application
    secrets:


  server:

    # Image to be used by the deployment to create the pod
    image: juspaydotin/hyperswitch-router:beta
    # Number of replicas to be used for the application
    replicas: 3
    # Wait time allowed for the deployment before the deployment is marked as failed
    progressDeadlineSeconds: 600
    # The strategy that can be used to replace the old pods by new ones
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    # Specify affinity for nodes to which the pods should start on
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - generic-compute
    # The time kubernetes will wait after sending the termination signal to the pods
    terminationGracePeriodSeconds: 30
    # Annotations that are to be added to the pods (extends global configuration)
    podAnnotations:
      traffic_sidecar_istio_io_excludeOutboundIPRanges: 
    # Annotations that are to be added the the deployments (extends global configuration)
    annotations:
      deployment.kubernetes.io/revision: "1"
    # Labels to be added to the deployment's (match labels) and their pods (extends global configuration)
    labels:
      app: hyperswitch-server
    # service account annotations to be used
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: 
    # Environmant variables that are to be used by the hyperswitch application service this will extend the existing global configuration
    env:
      binary: router
  consumer:
    # Image to be used by the deployment to create the pod
    image: juspaydotin/hyperswitch-consumer:beta
    # Number of replicas to be used for the application
    replicas: 3
    # Wait time allowed for the deployment before the deployment is marked as failed
    progressDeadlineSeconds: 600
    # The strategy that can be used to replace the old pods by new ones
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    # Specify affinity for nodes to which the pods should start on
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - generic-compute
    # The time kubernetes will wait after sending the termination signal to the pods
    terminationGracePeriodSeconds: 30
    # Annotations that are to be added to the pods (extends global configuration)
    podAnnotations:
      traffic_sidecar_istio_io_excludeOutboundIPRanges: 
    # Annotations that are to be added the the deployments (extends global configuration)
    annotations:
      deployment.kubernetes.io/revision: "1"
    # Labels to be added to the deployment's (match labels) and their pods (extends global configuration)
    labels:
      app: hyperswitch-consumer
    # service account annotations to be used
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: 
    # Environmant variables that are to be used by the hyperswitch application service this will extend the existing global configuration
    env:
      binary: consumer


  producer:
    # Image to be used by the deployment to create the pod
    image: juspaydotin/hyperswitch-producer:beta
    # Number of replicas to be used for the application
    replicas: 1
    # Wait time allowed for the deployment before the deployment is marked as failed
    progressDeadlineSeconds: 600
    # The strategy that can be used to replace the old pods by new ones
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    # Specify affinity for nodes to which the pods should start on
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node-type
                operator: In
                values:
                  - generic-compute
    # The time kubernetes will wait after sending the termination signal to the pods
    terminationGracePeriodSeconds: 30
    # Annotations that are to be added to the pods (extends global configuration)
    podAnnotations:
      traffic_sidecar_istio_io_excludeOutboundIPRanges: 
    # Annotations that are to be added the the deployments (extends global configuration)
    annotations:
      deployment.kubernetes.io/revision: "1"
    # Labels to be added to the deployment's (match labels) and their pods (extends global configuration)
    labels:
      app: hyperswitch-producer
    # service account annotations to be used
    serviceAccountAnnotations:
      eks.amazonaws.com/role-arn: 
    # Environmant variables that are to be used by the hyperswitch application service this will extend the existing global configuration
    env:
      binary: producer

# configuration values to be used by the service that is connected to the hyperswitch server
services:
  # labels to be used bht the service
  labels:
    app: hyperswitch-server

  # port to be used for routing http traffic
  httpPort: 80


# ingress:
#   # should we create a new ingress
#   enabled: true
  
#   # name of the ingress
#   name: hyperswitch-ingress

#   # annotation that are to be used by the ingress
#   annotations:
#     alb.ingress.kubernetes.io/backend-protocol-version: HTTP1

redis:
  host: "asdas"
  replicaCount: 1

loadBalancer: 
  targetSecurityGroup: 

db: 
  host: "asdsad"

loki:
  auth_enabled: false
