apiVersion: v1
kind: ConfigMap
metadata:
  name: router-cm-{{.Release.Name }}
data:
  router.toml: |
    {{- if eq .Values.application.server.run_env "production" -}}
    {{ .Files.Get "configs/misc.toml" | nindent 4 }}
    {{ .Files.Get "configs/router-production.toml" | nindent 4 }}
    {{- else -}}
    {{ .Files.Get "configs/misc.toml" | nindent 4 }}
    {{ .Files.Get "configs/router-sandbox.toml" | nindent 4 }}
    {{- end }}