
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hyperswitch-router-role
  namespace: {{ .Release.Namespace }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hyperswitch-pdb
  namespace: {{ .Release.Namespace }}
spec:
  minAvailable: 1
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
        - {{ .Values.application.sdk.labels.app }}
        - {{ .Values.application.server.labels.app }}
        - {{ .Values.application.producer.labels.app }}
        - {{ .Values.application.controlCenter.labels.app }}
        - "hyperswitch-web"
        - hyperloader-build-job
        - create-hyperswitch-db
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: 
    matchExpressions:
      - key: app
        operator: In
        values:
        - {{ .Values.application.sdk.labels.app }}
        - {{ .Values.application.server.labels.app }}
        - {{ .Values.application.producer.labels.app }}
        - {{ .Values.application.controlCenter.labels.app }}
        - "hyperswitch-web"
        - hyperloader-build-job
        - create-hyperswitch-db
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
  egress:
  - to:
    - podSelector: {}
---