apiVersion: batch/v1
kind: Job
metadata:
  name: create-hyperswitch-db-{{ $.Values.services.router.version }}
  namespace: {{ $.Release.Namespace }}
  annotations:
spec:
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      labels:
        app: create-hyperswitch-db
    spec:
      containers:
      - name: run-hyperswitch-db-migration
        image: christophwurst/diesel-cli:latest
        imagePullPolicy: Always
        command: ['sh', '-c']
        args:
        - |
          apt update
          apt install -y git
          git clone --branch $ROUTER_VERSION https://github.com/juspay/hyperswitch.git
          cd hyperswitch
          diesel migration --database-url postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@$POSTGRES_HOST:5432/$DBNAME run
          echo "Completed hyperswitch database migration"
        securityContext:
          privileged: false
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
            ephemeral-storage: "1Gi"
          limits:
            cpu: 1000m
            memory: 1000Mi
            ephemeral-storage: "2Gi"
        env:
        - name: ROUTER_VERSION
          value: {{ .Values.services.router.version }}
        - name: POSTGRES_HOST
          value: {{ .Values.db.host }}
        - name: DBNAME
          value: {{ .Values.db.name }}
        - name: POSTGRES_USER
          value: {{ .Values.db.user_name }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hyperswitch-secrets
              key: DB_PASS
      restartPolicy: Never
