# loadbalancer security group
# @ignored
loadBalancer:
  targetSecurityGroup: &lb_security_group lg-security-group

# @ignored
service:
  type: ClusterIP
  port: 80

# @ignored
services:
  router:
    host: &router_host http://localhost:8080
  sdk:
    host: &web_sdk_host http://localhost:9050

global:
  tolerations: []
  # @ignored
  # Eg.
  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: node-type
  #               operator: In
  #               values:
  #                 - generic-compute
  affinity: {}

# @ignored
hyperswitch-web:
  fullnameOverride: "hyperswitch-web"
  enabled: true
  sdkDemo:
    enabled: false
  image:
    pullPolicy: IfNotPresent
  podAnnotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
  autoBuild:
    enable: true
    forceBuild: true
    gitCloneParam:
      gitVersion: 0.123.0
    nginxConfig:
      extraPath: v1
    buildParam:
      envSdkUrl: *web_sdk_host
      envBackendUrl: *router_host
      envLogsUrl: http://localhost:3103
  service:
    port: 9050
  loadBalancer:
    targetSecurityGroup: "loadbalancer-sg"
  tolerations: []
  ingress:
    enabled: true
    className: "alb"
    apiVersion: networking.k8s.io/v1
    annotations:
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/backend-protocol-version: HTTP1
      alb.ingress.kubernetes.io/group.name: hyperswitch-web-alb-ingress-group
      alb.ingress.kubernetes.io/ip-address-type: ipv4
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
      alb.ingress.kubernetes.io/load-balancer-name: hyperswitch-web
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/security-groups: *lb_security_group
      alb.ingress.kubernetes.io/tags: stack=hyperswitch-lb
      alb.ingress.kubernetes.io/target-type: ip
    hosts:
      - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hyperswitch-web
                port:
                  number: 80
# @ignored
hyperswitch-app:
  initDB:
    enable: true
  loadBalancer:
    targetSecurityGroup: *lb_security_group
  services:
    router:
      version: v1.115.0
      image: docker.juspay.io/juspaydotin/hyperswitch-router:v1.115.0
      host: *router_host
    consumer:
      image: docker.juspay.io/juspaydotin/hyperswitch-consumer:v1.115.0
    producer:
      image: docker.juspay.io/juspaydotin/hyperswitch-producer:v1.115.0
    controlCenter:
      image: docker.juspay.io/juspaydotin/hyperswitch-control-center:v1.37.2
    sdk:
      host: *web_sdk_host
      version: 0.123.0
      subversion: v1
  server:
    replicas: 1
    secrets:
      # Follow https://github.com/juspay/hyperswitch/tree/main/crates/analytics#setting-up-forex-apis to get the forex api key
      forex_api_key: forex_api_key
      forex_fallback_api_key: forex_fallback_api_key
    locker:
      locker_enabled: true
    run_env: sandbox
    email:
      active_email_client: SMTP
  controlCenter:
    env:
      default__features__email: "true"
      default__features__totp: "true"
      default__features__test_processors: "true"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80

  hyperswitch-card-vault:
    enabled: true
    server:
      image: docker.juspay.io/juspaydotin/hyperswitch-card-vault:v0.6.5-dev
      tenant_secrets:
        hyperswitch:
          master_key: "8283d68fdbd89a78aef9bed8285ed1cd9310012f660eefbad865f20a3f3dd9498f06147da6a7d9b84677cafca95024990b3d2296fbafc55e10dd76df"
          public_key: ""
          schema: "public"

    initDB:
      enable: true
    postgresql:
      primary:
        tolerations: []
  redis:
    master:
      tolerations: []
  postgresql:
    primary:
      tolerations: []
    readReplicas:
      tolerations: []
  kafka:
    controller:
      tolerations: []
    broker:
      tolerations: []
    zookeeper:
      tolerations: []
    provisioning:
      tolerations: []
  clickhouse:
    tolerations: []
    zookeeper:
      tolerations: []
  mailhog:
    tolerations: []
  vector:
    tolerations: []

hyperswitch-monitoring:
  enabled: true
  # Global tolerations for monitoring components
  global:
    tolerations: []
  # Component-specific tolerations
  kube-prometheus-stack:
    prometheus:
      prometheusSpec:
        tolerations: []
    grafana:
      tolerations: []
    alertmanager:
      alertmanagerSpec:
        tolerations: []
  loki:
    singleBinary:
      tolerations: []
  promtail:
    tolerations: []
  opentelemetry-collector:
    tolerations: []

# @ignored
hyperswitch-ucs:
  enabled: true
  fullnameOverride: "hyperswitch-ucs"
  image:
    repository: ghcr.io/juspay/connector-service
    pullPolicy: IfNotPresent
    tag: "main-b1487cb"
  imagePullSecrets: []
  nameOverride: ""

  serviceAccount:
    create: true
    annotations: {}
    name: ""

  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}

  service:
    type: ClusterIP
    grpc:
      port: 8000
      targetPort: 8000
    metrics:
      port: 8080
      targetPort: 8080

  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: hyperswitch-ucs.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage:
      80
      # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}
  tolerations: []
  affinity: {}

  # Environment variables
  env:
    - name: CS__LOG__CONSOLE__ENABLED
      value: "true"
    - name: CS__LOG__CONSOLE__LEVEL
      value: "DEBUG"
    - name: CS__LOG__CONSOLE__LOG_FORMAT
      value: "json"
    - name: CS__SERVER__HOST
      value: "0.0.0.0"
    - name: CS__SERVER__PORT
      value: "8000"
    - name: CS__SERVER__TYPE
      value: "grpc"
    - name: CS__METRICS__HOST
      value: "0.0.0.0"
    - name: CS__METRICS__PORT
      value: "8080"
    - name: CS__CONNECTORS__ADYEN__BASE_URL
      value: "https://{{merchant_endpoint_prefix}}-checkout-live.adyenpayments.com/checkout/"
    - name: CS__CONNECTORS__ADYEN__DISPUTE_BASE_URL
      value: "https://{{merchant_endpoint_prefix}}-ca-live.adyen.com/"
    - name: CS__CONNECTORS__RAZORPAY__BASE_URL
      value: "https://api.razorpay.com/"
    - name: CS__CONNECTORS__FISERV__BASE_URL
      value: "https://cert.api.fiservapps.com/"
    - name: CS__CONNECTORS__ELAVON__BASE_URL
      value: "https://api.convergepay.com/VirtualMerchant/"
    - name: CS__CONNECTORS__XENDIT__BASE_URL
      value: "https://api.xendit.co/"
    - name: CS__CONNECTORS__RAZORPAYV2__BASE_URL
      value: "https://api.razorpay.com/"
    - name: CS__CONNECTORS__CHECKOUT__BASE_URL
      value: "https://api.checkout.com/"
    - name: CS__CONNECTORS__AUTHORIZEDOTNET__BASE_URL
      value: "https://api.authorize.net/xml/v1/request.api/"
    - name: CS__PROXY__HTTPS_URL
      value: ""
    - name: CS__PROXY__HTTP_URL
      value: ""
    - name: CS__PROXY__IDLE_POOL_CONNECTION_TIMEOUT
      value: "90"
    - name: CS__PROXY__BYPASS_PROXY_URLS
      value: "localhost,local"
