apiVersion: v1
kind: Service
metadata:
  labels:
    app: hyperswitch-server
  name: hyperswitch-server
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: 10.100.1.1
  clusterIPs:
  - 10.100.1.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 443
    protocol: TCP
    targetPort: 8080
  selector:
    app: hyperswitch-server
  sessionAffinity: None
  type: ClusterIP

