apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-new-cm
  namespace: kube-analytics
data:
    fluent.conf: |
      {{ .Files.Get "configs/fluent.conf" | nindent 6 }}
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-new
  namespace: kube-analytics
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        kubernetes.io/cluster-service: "true"
        version: v1
    spec:
      containers:
      - env:
        - name: FLUENT_ELASTICSEARCH_SED_DISABLE
          value: "true"
        - name: FLUENT_ELASTICSEARCH_HOST
          value: vpc-hyperswitch-els-75gkb4fkwnaehqogungyvm7iqe.us-east-1.es.amazonaws.com
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "443"
        - name: FLUENT_ELASTICSEARCH_SCHEME
          value: https
        - name: FLUENT_UID
          value: "0"
        - name: CLUSTER_NAME
          value: hyperswitch-eks
        - name: FLUENTD_NAME
          value: hyperswitch-els
        - name: AWS_STS_REGIONAL_ENDPOINTS
          value: regional
        image: docker.io/fluent/fluentd-kubernetes-daemonset:v1.16-debian-opensearch-2
        imagePullPolicy: IfNotPresent
        name: fluentd-new
        resources:
          limits:
            cpu: "1"
            memory: 1200Mi
          requests:
            cpu: 200m
            memory: 150Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /var/lib/docker/containers
          name: varlibdockercontainers
          readOnly: true
        - mountPath: /fluentd/etc
          name: fluentd-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluentd
      serviceAccountName: fluentd
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - configMap:
          defaultMode: 420
          name: fluentd-new-cm
        name: fluentd-config
      - hostPath:
          path: /var/log
          type: ""
        name: varlog
      - hostPath:
          path: /var/lib/docker/containers
          type: ""
        name: varlibdockercontainers
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 25%
    type: RollingUpdate
status:
  currentNumberScheduled: 24
  desiredNumberScheduled: 24
  numberAvailable: 23
  numberMisscheduled: 4
  numberReady: 23
  numberUnavailable: 1
  observedGeneration: 2
  updatedNumberScheduled: 24