apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: kube-analytics
  resourceVersion: "683751"
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - containers
  - namespaces
  verbs:
  - get
  - list
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - deployments/scale
  verbs:
  - get
  - list