apiVersion: v1
data:
  BACH__KEYS__TEMP_CARD_KEY: ""
  BACH_READ_USER_PWD: ""
  ROUTER__ANALYTICS__SQLX__USERNAME: {{ include "postgresqlreplica.username" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__HOST: {{ include "postgresqlreplica.host" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__PORT: {{ include "postgresqlreplica.port" . | b64enc }}
  ROUTER__ANALYTICS__SQLX__DBNAME: {{ include "postgresql.database" . | b64enc }}
  ROUTER__ANALYTICS__CLICKHOUSE__USERNAME: {{ .Values.application.server.analytics.clickhouse.username | b64enc }}
  ROUTER__ANALYTICS__CLICKHOUSE__DATABASE_NAME: {{ .Values.application.server.analytics.clickhouse.database | b64enc }}
  ROUTER__ANALYTICS__CLICKHOUSE__HOST: {{ .Values.application.server.analytics.clickhouse.host | b64enc }}
  {{- if not .Values.clickhouse.enabled }}
  ROUTER__ANALYTICS__CLICKHOUSE__PASSWORD: {{ .Values.analytics.clickhouse.password | b64enc | quote }}
  {{- end }}
  ROUTER__EMAIL__AWS_REGION: {{ .Values.application.server.email.aws_region | b64enc }}
  ROUTER__EMAIL__SENDER_EMAIL: {{ .Values.application.server.email.sender_email | b64enc }}
  ROUTER__EMAIL__RECON_RECIPIENT_EMAIL: {{ .Values.application.server.email.recon_recipient_email | b64enc }}
  ROUTER__EMAIL__PROD_INTENT_RECIPIENT_EMAIL: {{ .Values.application.server.email.prod_intent_recipient_email | b64enc }}
  ROUTER__EMAIL__SMTP__HOST: {{ .Values.application.server.email.smtp.host | b64enc }}
  ROUTER__EMAIL__SMTP__PORT: {{ .Values.application.server.email.smtp.port | b64enc }}
  {{- if .Values.application.server.email.smtp.username }}
  ROUTER__EMAIL__SMTP__USERNAME: {{ .Values.application.server.email.smtp.username | b64enc }}
  ROUTER__EMAIL__SMTP__PASSWORD: {{ .Values.application.server.email.smtp.password | b64enc }}  
  {{- end }}
  ROUTER__EMAIL__AWS_SES__EMAIL_ROLE_ARN: {{ .Values.application.server.email.aws_ses.email_role_arn | b64enc }}
  ROUTER__EMAIL__AWS_SES__STS_ROLE_SESSION_NAME: {{ .Values.application.server.email.aws_ses.sts_role_session_name | b64enc }}
  ROUTER__API_KEYS__KMS_ENCRYPTED_HASH_KEY: {{ .Values.application.server.secrets.kms_encrypted_api_hash_key | toString | b64enc }}
  ROUTER__JWEKEY__TUNNEL_PRIVATE_KEY: {{ .Values.application.server.secrets.kms_jwekey_tunnel_private_key | b64enc }}
  ROUTER__JWEKEY__VAULT_ENCRYPTION_KEY: {{ .Values.application.server.secrets.kms_jwekey_vault_encryption_key | b64enc }}
  ROUTER__JWEKEY__VAULT_PRIVATE_KEY: {{ .Values.application.server.secrets.kms_jwekey_vault_private_key | b64enc }}
  ROUTER__KMS__KEY_ID: {{ .Values.application.server.secrets.kms_key_id | b64enc }}
  ROUTER__KMS__REGION: {{ .Values.application.server.secrets.kms_key_region | b64enc }}
  ROUTER__JWEKEY__RUST_LOCKER_ENCRYPTION_KEY: {{ .Values.application.server.secrets.kms_jwekey_rust_locker_encryption_key | b64enc }}
  ROUTER__SECRETS__ADMIN_API_KEY: {{ .Values.application.server.secrets.admin_api_key | b64enc }}
  ROUTER__SECRETS__JWT_SECRET: {{ .Values.application.server.secrets.jwt_secret | b64enc}}
  ROUTER__SECRETS__MASTER_ENC_KEY: {{ .Values.application.server.secrets.master_enc_key | b64enc }}
  ROUTER__CONNECTOR_ONBOARDING__PAYPAL__CLIENT_ID: {{ .Values.application.server.secrets.kms_connector_onboarding_paypal_client_id | b64enc}}
  ROUTER__CONNECTOR_ONBOARDING__PAYPAL__CLIENT_SECRET: {{ .Values.application.server.secrets.kms_connector_onboarding_paypal_client_secret | b64enc}}
  ROUTER__CONNECTOR_ONBOARDING__PAYPAL__PARTNER_ID: {{ .Values.application.server.secrets.kms_connector_onboarding_paypal_partner_id | b64enc}}
  ROUTER__APPLEPAY_DECRYPT_KEYS__APPLE_PAY_MERCHANT_CERT: {{ .Values.application.server.secrets.apple_pay_merchant_cert | b64enc}}
  ROUTER__APPLEPAY_DECRYPT_KEYS__APPLE_PAY_MERCHANT_CERT_KEY: {{ .Values.application.server.secrets.apple_pay_merchant_cert_key | b64enc}}
  ROUTER__APPLEPAY_DECRYPT_KEYS__APPLE_PAY_PPC: {{ .Values.application.server.secrets.apple_pay_ppc | b64enc}}
  ROUTER__APPLEPAY_DECRYPT_KEYS__APPLE_PAY_PPC_KEY: {{ .Values.application.server.secrets.apple_pay_ppc_key | b64enc}}
  ROUTER__APPLEPAY_MERCHANT_CONFIGS__MERCHANT_CERT: {{ .Values.application.server.secrets.apple_pay_merchant_conf_merchant_cert | b64enc}}
  ROUTER__APPLEPAY_MERCHANT_CONFIGS__MERCHANT_CERT_KEY: {{ .Values.application.server.secrets.apple_pay_merchant_conf_merchant_cert_key | b64enc}}
  ROUTER__APPLEPAY_MERCHANT_CONFIGS__COMMON_MERCHANT_IDENTIFIER: {{ .Values.application.server.secrets.apple_pay_merchant_conf_merchant_id | b64enc}}
  ROUTER__PAYMENT_METHOD_AUTH__PM_AUTH_KEY: {{ .Values.application.server.secrets.pm_auth_key | b64enc}}
  ROUTER__API_KEYS__HASH_KEY: {{ .Values.application.server.secrets.api_hash_key | b64enc}}
  ROUTER__FOREX_API__API_KEY: {{ .Values.application.server.secrets.forex_api_key | b64enc }}
  ROUTER__FOREX_API__FALLBACK_API_KEY: {{ .Values.application.server.secrets.forex_fallback_api_key | b64enc }}

kind: Secret
metadata:
  name: hyperswitch-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
